import Head from 'next/head';
import Image from 'next/image';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillLike,
  AiFillHeart
} from 'react-icons/ai';
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode ] = useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jonnydevs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className='text-2xl flex dark:text-cyan-300'>
            <AiFillHeart className='text-3xl mr-3 dark:text-cyan-300'/>jonnydevs
            <AiFillLike className='text-3xl ml-3 dark:text-cyan-300' />
            </h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' /></li>
              <li><a  className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>jonnydevs</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Full stack developer</h3>
            <p className='text-md py-5 leading-8 md:text-xl max-w-lg mx-auto dark:text-white'>
              Freelancer providing services for all your programming needs. Join me down below and let's crack this together.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-2 dark:text-cyan-300'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Since the begining of my journey as a full stack developer, I've gained alot of <span className='text-teal-500'>experience</span>  and  
              <span className='text-teal-500'> mastery</span> of my dev tools and have worked on both the front-end and back-end fields of technology.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I offer a wide range of services, incliding design and mentorship.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center bg-gray-200 shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800'>
              <Image src={design} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-cyan-300'>Stunning designs</h3>
              <p className='py-1 dark:text-white'>
                I create amazing and stunning designs that suit the design theory.
              </p>
              <h4 className='py-4 text-teal-600 dark:text-cyan-300'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Illustrator</p>
              <p className='text-gray-800 py-1 dark:text-white'>Figma</p>
            </div>
            <div className='text-center bg-gray-200 shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800'>
              <Image src={code} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-cyan-300'>Quality Software</h3>
              <p className='py-1 dark:text-white'>
                I create and design software that suits the needs of my client and users.
              </p>
              <h4 className='py-4 text-teal-600'>Tools that I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Js Frameworks</p>
              <p className='text-gray-800 py-1 dark:text-white'>VS Code</p>
              <p className='text-gray-800 py-1 dark:text-white'>Version contol systems</p>
            </div>
            <div className='text-center bg-gray-200 shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800'>
              <Image src={consulting} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-cyan-300'>Amazing Mentorship</h3>
              <p className='py-1 dark:text-white'>
                I offer amazing mentorship on various software development topics.
              </p>
              <h4 className='py-4 text-teal-600'>Mentorship programs</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Weekly newsletter</p>
              <p className='text-gray-800 py-1 dark:text-white'>Email subscription</p>
              <p className='text-gray-800 py-1 dark:text-white'>Twitter space</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-2 dark:text-cyan-300'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Since the begining of my journey as a full stack developer, I've gained alot of <span className='text-teal-500'>experience</span>  and  
              <span className='text-teal-500'> mastery</span> of my dev tools and have worked on both the front-end and back-end fields of technology.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I offer a wide range of services, incliding design and mentorship.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row
          lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive" />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
